[project]
name = "stack-literal-eval"
version = "0.1.0"
description = "Stack-based `ast.literal_eval`"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.9.2",
    "pyperf>=2.8.0",
    "pytest>=8.3.3",
]

[tool.pytest.ini_options]
testpaths = ["test_main.py"]
